// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: likes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getLike = `-- name: GetLike :one
SELECT user_id, quote_id FROM likes WHERE User_ID = $1 AND Quote_ID = $2
`

type GetLikeParams struct {
	UserID  uuid.UUID
	QuoteID uuid.UUID
}

func (q *Queries) GetLike(ctx context.Context, arg GetLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, getLike, arg.UserID, arg.QuoteID)
	var i Like
	err := row.Scan(&i.UserID, &i.QuoteID)
	return i, err
}
