// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: quotes.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getQuote = `-- name: GetQuote :one
SELECT id, created_at, updated_at, user_id, content FROM quotes WHERE ID = $1
`

func (q *Queries) GetQuote(ctx context.Context, id uuid.UUID) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getQuote, id)
	var i Quote
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Content,
	)
	return i, err
}
