// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tags.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE ID = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, created_at, updated_at, name FROM tags WHERE ID = $1
`

func (q *Queries) GetTag(ctx context.Context, id uuid.UUID) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}

const postTag = `-- name: PostTag :one
INSERT INTO tags (ID, Created_At, Updated_At, Name)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, name
`

type PostTagParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
}

func (q *Queries) PostTag(ctx context.Context, arg PostTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, postTag,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
